


[character]
use_symbol_for_status = true
success_symbol = "[❯](bold purple)"
error_symbol = "[✗](bold red) "

[directory]
truncate_to_repo = false # truncates directory to root folder if in github repo
style = "blue"
read_only = ""

[nix_shell]
format = ' [$name]($style) '

[username]
format = "[$user]($style)"

[hostname]
ssh_only = true

[git_branch]
format = "[ $branch](#6a6a6a)"

[git_status]
format = " [$all_status](fg:#FFC0CB)[$ahead_behind](fg:cyan) "
all_status = "$conflicted $stashed $deleted $modified $staged $untracked"
staged = "•"
modified = "~"
untracked = "*"
deleted = "x"
stashed = ""


[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
